### ISSUE TITLE
Kotlin script not working

### ISSUE THREAD

**Issue by g123k** [paug/video-tools#10]
Hi,

After saving my credentials and invoking the Kt script, I have this error:

 ```
kscripts ./am_youtube_tool.kts             
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at Main_Am_youtube_tool$Companion.main(Main_Am_youtube_tool.kt:6)
        at Main_Am_youtube_tool.main(Main_Am_youtube_tool.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:70)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:188)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:198)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at Am_youtube_tool$updateCommand$1.<clinit>(am_youtube_tool.kts:218)
        at Am_youtube_tool.<init>(am_youtube_tool.kts:217)
        ... 13 more
```

**Comment by martinbonnin** [comment]
I think we need to write another script in .net 🙃

**Comment by martinbonnin** [comment]
I think it should work now but I haven't done anything to fix that particular issue 🤔 . Looks like it's similar to https://youtrack.jetbrains.com/issue/KT-37435.

**Comment by martinbonnin** [comment]
Closing as stale
